//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dcsrt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>\'ll</string>\r\n  <string>\'tis</string>\r\n  <string>\'twas</string>\r\n  <string" +
            ">\'ve</string>\r\n  <string>10</string>\r\n  <string>39</string>\r\n  <string>a</string" +
            ">\r\n  <string>a\'s</string>\r\n  <string>able</string>\r\n  <string>ableabout</string>" +
            "\r\n  <string>about</string>\r\n  <string>above</string>\r\n  <string>abroad</string>\r" +
            "\n  <string>abst</string>\r\n  <string>accordance</string>\r\n  <string>according</st" +
            "ring>\r\n  <string>accordingly</string>\r\n  <string>across</string>\r\n  <string>act<" +
            "/string>\r\n  <string>actually</string>\r\n  <string>ad</string>\r\n  <string>added</s" +
            "tring>\r\n  <string>adj</string>\r\n  <string>adopted</string>\r\n  <string>ae</string" +
            ">\r\n  <string>af</string>\r\n  <string>affected</string>\r\n  <string>affecting</stri" +
            "ng>\r\n  <string>affects</string>\r\n  <string>after</string>\r\n  <string>afterwards<" +
            "/string>\r\n  <string>ag</string>\r\n  <string>again</string>\r\n  <string>against</st" +
            "ring>\r\n  <string>ago</string>\r\n  <string>ah</string>\r\n  <string>ahead</string>\r\n" +
            "  <string>ai</string>\r\n  <string>ain\'t</string>\r\n  <string>aint</string>\r\n  <str" +
            "ing>al</string>\r\n  <string>all</string>\r\n  <string>allow</string>\r\n  <string>all" +
            "ows</string>\r\n  <string>almost</string>\r\n  <string>alone</string>\r\n  <string>alo" +
            "ng</string>\r\n  <string>alongside</string>\r\n  <string>already</string>\r\n  <string" +
            ">also</string>\r\n  <string>although</string>\r\n  <string>always</string>\r\n  <strin" +
            "g>am</string>\r\n  <string>amid</string>\r\n  <string>amidst</string>\r\n  <string>amo" +
            "ng</string>\r\n  <string>amongst</string>\r\n  <string>amoungst</string>\r\n  <string>" +
            "amount</string>\r\n  <string>an</string>\r\n  <string>and</string>\r\n  <string>announ" +
            "ce</string>\r\n  <string>another</string>\r\n  <string>any</string>\r\n  <string>anybo" +
            "dy</string>\r\n  <string>anyhow</string>\r\n  <string>anymore</string>\r\n  <string>an" +
            "yone</string>\r\n  <string>anything</string>\r\n  <string>anyway</string>\r\n  <string" +
            ">anyways</string>\r\n  <string>anywhere</string>\r\n  <string>ao</string>\r\n  <string" +
            ">apart</string>\r\n  <string>apparently</string>\r\n  <string>appear</string>\r\n  <st" +
            "ring>appreciate</string>\r\n  <string>appropriate</string>\r\n  <string>approximatel" +
            "y</string>\r\n  <string>aq</string>\r\n  <string>ar</string>\r\n  <string>are</string>" +
            "\r\n  <string>area</string>\r\n  <string>areas</string>\r\n  <string>aren</string>\r\n  " +
            "<string>aren\'t</string>\r\n  <string>arent</string>\r\n  <string>arise</string>\r\n  <" +
            "string>around</string>\r\n  <string>arpa</string>\r\n  <string>as</string>\r\n  <strin" +
            "g>aside</string>\r\n  <string>ask</string>\r\n  <string>asked</string>\r\n  <string>as" +
            "king</string>\r\n  <string>asks</string>\r\n  <string>associated</string>\r\n  <string" +
            ">at</string>\r\n  <string>au</string>\r\n  <string>auth</string>\r\n  <string>availabl" +
            "e</string>\r\n  <string>aw</string>\r\n  <string>away</string>\r\n  <string>awfully</s" +
            "tring>\r\n  <string>az</string>\r\n  <string>b</string>\r\n  <string>ba</string>\r\n  <s" +
            "tring>back</string>\r\n  <string>backed</string>\r\n  <string>backing</string>\r\n  <s" +
            "tring>backs</string>\r\n  <string>backward</string>\r\n  <string>backwards</string>\r" +
            "\n  <string>bb</string>\r\n  <string>bd</string>\r\n  <string>be</string>\r\n  <string>" +
            "became</string>\r\n  <string>because</string>\r\n  <string>become</string>\r\n  <strin" +
            "g>becomes</string>\r\n  <string>becoming</string>\r\n  <string>been</string>\r\n  <str" +
            "ing>before</string>\r\n  <string>beforehand</string>\r\n  <string>began</string>\r\n  " +
            "<string>begin</string>\r\n  <string>beginning</string>\r\n  <string>beginnings</stri" +
            "ng>\r\n  <string>begins</string>\r\n  <string>behind</string>\r\n  <string>being</stri" +
            "ng>\r\n  <string>beings</string>\r\n  <string>believe</string>\r\n  <string>below</str" +
            "ing>\r\n  <string>beside</string>\r\n  <string>besides</string>\r\n  <string>best</str" +
            "ing>\r\n  <string>better</string>\r\n  <string>between</string>\r\n  <string>beyond</s" +
            "tring>\r\n  <string>bf</string>\r\n  <string>bg</string>\r\n  <string>bh</string>\r\n  <" +
            "string>bi</string>\r\n  <string>big</string>\r\n  <string>bill</string>\r\n  <string>b" +
            "illion</string>\r\n  <string>biol</string>\r\n  <string>bj</string>\r\n  <string>bm</s" +
            "tring>\r\n  <string>bn</string>\r\n  <string>bo</string>\r\n  <string>both</string>\r\n " +
            " <string>bottom</string>\r\n  <string>br</string>\r\n  <string>brief</string>\r\n  <st" +
            "ring>briefly</string>\r\n  <string>bs</string>\r\n  <string>bt</string>\r\n  <string>b" +
            "ut</string>\r\n  <string>buy</string>\r\n  <string>bv</string>\r\n  <string>bw</string" +
            ">\r\n  <string>by</string>\r\n  <string>bz</string>\r\n  <string>c</string>\r\n  <string" +
            ">c\'mon</string>\r\n  <string>c\'s</string>\r\n  <string>ca</string>\r\n  <string>call</" +
            "string>\r\n  <string>came</string>\r\n  <string>can</string>\r\n  <string>can\'t</strin" +
            "g>\r\n  <string>cannot</string>\r\n  <string>cant</string>\r\n  <string>caption</strin" +
            "g>\r\n  <string>case</string>\r\n  <string>cases</string>\r\n  <string>cause</string>\r" +
            "\n  <string>causes</string>\r\n  <string>cc</string>\r\n  <string>cd</string>\r\n  <str" +
            "ing>certain</string>\r\n  <string>certainly</string>\r\n  <string>cf</string>\r\n  <st" +
            "ring>cg</string>\r\n  <string>ch</string>\r\n  <string>changes</string>\r\n  <string>c" +
            "i</string>\r\n  <string>ck</string>\r\n  <string>cl</string>\r\n  <string>clear</strin" +
            "g>\r\n  <string>clearly</string>\r\n  <string>click</string>\r\n  <string>cm</string>\r" +
            "\n  <string>cmon</string>\r\n  <string>cn</string>\r\n  <string>co</string>\r\n  <strin" +
            "g>co.</string>\r\n  <string>com</string>\r\n  <string>come</string>\r\n  <string>comes" +
            "</string>\r\n  <string>computer</string>\r\n  <string>con</string>\r\n  <string>concer" +
            "ning</string>\r\n  <string>consequently</string>\r\n  <string>consider</string>\r\n  <" +
            "string>considering</string>\r\n  <string>contain</string>\r\n  <string>containing</s" +
            "tring>\r\n  <string>contains</string>\r\n  <string>copy</string>\r\n  <string>correspo" +
            "nding</string>\r\n  <string>could</string>\r\n  <string>could\'ve</string>\r\n  <string" +
            ">couldn</string>\r\n  <string>couldn\'t</string>\r\n  <string>couldnt</string>\r\n  <st" +
            "ring>course</string>\r\n  <string>cr</string>\r\n  <string>cry</string>\r\n  <string>c" +
            "s</string>\r\n  <string>cu</string>\r\n  <string>currently</string>\r\n  <string>cv</s" +
            "tring>\r\n  <string>cx</string>\r\n  <string>cy</string>\r\n  <string>cz</string>\r\n  <" +
            "string>d</string>\r\n  <string>dare</string>\r\n  <string>daren\'t</string>\r\n  <strin" +
            "g>darent</string>\r\n  <string>date</string>\r\n  <string>de</string>\r\n  <string>dea" +
            "r</string>\r\n  <string>definitely</string>\r\n  <string>describe</string>\r\n  <strin" +
            "g>described</string>\r\n  <string>despite</string>\r\n  <string>detail</string>\r\n  <" +
            "string>did</string>\r\n  <string>didn</string>\r\n  <string>didn\'t</string>\r\n  <stri" +
            "ng>didnt</string>\r\n  <string>differ</string>\r\n  <string>different</string>\r\n  <s" +
            "tring>differently</string>\r\n  <string>directly</string>\r\n  <string>dj</string>\r\n" +
            "  <string>dk</string>\r\n  <string>dm</string>\r\n  <string>do</string>\r\n  <string>d" +
            "oes</string>\r\n  <string>doesn</string>\r\n  <string>doesn\'t</string>\r\n  <string>do" +
            "esnt</string>\r\n  <string>doing</string>\r\n  <string>don</string>\r\n  <string>don\'t" +
            "</string>\r\n  <string>done</string>\r\n  <string>dont</string>\r\n  <string>doubtful<" +
            "/string>\r\n  <string>down</string>\r\n  <string>downed</string>\r\n  <string>downing<" +
            "/string>\r\n  <string>downs</string>\r\n  <string>downwards</string>\r\n  <string>due<" +
            "/string>\r\n  <string>during</string>\r\n  <string>dz</string>\r\n  <string>e</string>" +
            "\r\n  <string>each</string>\r\n  <string>early</string>\r\n  <string>ec</string>\r\n  <s" +
            "tring>ed</string>\r\n  <string>edu</string>\r\n  <string>ee</string>\r\n  <string>effe" +
            "ct</string>\r\n  <string>eg</string>\r\n  <string>eh</string>\r\n  <string>eight</stri" +
            "ng>\r\n  <string>eighty</string>\r\n  <string>either</string>\r\n  <string>eleven</str" +
            "ing>\r\n  <string>else</string>\r\n  <string>elsewhere</string>\r\n  <string>empty</st" +
            "ring>\r\n  <string>end</string>\r\n  <string>ended</string>\r\n  <string>ending</strin" +
            "g>\r\n  <string>ends</string>\r\n  <string>enough</string>\r\n  <string>entirely</stri" +
            "ng>\r\n  <string>er</string>\r\n  <string>es</string>\r\n  <string>especially</string>" +
            "\r\n  <string>et</string>\r\n  <string>et-al</string>\r\n  <string>etc</string>\r\n  <st" +
            "ring>even</string>\r\n  <string>evenly</string>\r\n  <string>ever</string>\r\n  <strin" +
            "g>evermore</string>\r\n  <string>every</string>\r\n  <string>everybody</string>\r\n  <" +
            "string>everyone</string>\r\n  <string>everything</string>\r\n  <string>everywhere</s" +
            "tring>\r\n  <string>ex</string>\r\n  <string>exactly</string>\r\n  <string>example</st" +
            "ring>\r\n  <string>except</string>\r\n  <string>f</string>\r\n  <string>face</string>\r" +
            "\n  <string>faces</string>\r\n  <string>fact</string>\r\n  <string>facts</string>\r\n  " +
            "<string>fairly</string>\r\n  <string>far</string>\r\n  <string>farther</string>\r\n  <" +
            "string>felt</string>\r\n  <string>few</string>\r\n  <string>fewer</string>\r\n  <strin" +
            "g>ff</string>\r\n  <string>fi</string>\r\n  <string>fifteen</string>\r\n  <string>fift" +
            "h</string>\r\n  <string>fifty</string>\r\n  <string>fify</string>\r\n  <string>fill</s" +
            "tring>\r\n  <string>find</string>\r\n  <string>finds</string>\r\n  <string>fire</strin" +
            "g>\r\n  <string>first</string>\r\n  <string>five</string>\r\n  <string>fix</string>\r\n " +
            " <string>fj</string>\r\n  <string>fk</string>\r\n  <string>fm</string>\r\n  <string>fo" +
            "</string>\r\n  <string>followed</string>\r\n  <string>following</string>\r\n  <string>" +
            "follows</string>\r\n  <string>for</string>\r\n  <string>forever</string>\r\n  <string>" +
            "former</string>\r\n  <string>formerly</string>\r\n  <string>forth</string>\r\n  <strin" +
            "g>forty</string>\r\n  <string>forward</string>\r\n  <string>found</string>\r\n  <strin" +
            "g>four</string>\r\n  <string>fr</string>\r\n  <string>free</string>\r\n  <string>from<" +
            "/string>\r\n  <string>front</string>\r\n  <string>full</string>\r\n  <string>fully</st" +
            "ring>\r\n  <string>further</string>\r\n  <string>furthered</string>\r\n  <string>furth" +
            "ering</string>\r\n  <string>furthermore</string>\r\n  <string>furthers</string>\r\n  <" +
            "string>fx</string>\r\n  <string>g</string>\r\n  <string>ga</string>\r\n  <string>gave<" +
            "/string>\r\n  <string>gb</string>\r\n  <string>gd</string>\r\n  <string>ge</string>\r\n " +
            " <string>general</string>\r\n  <string>generally</string>\r\n  <string>get</string>\r" +
            "\n  <string>gets</string>\r\n  <string>getting</string>\r\n  <string>gf</string>\r\n  <" +
            "string>gg</string>\r\n  <string>gh</string>\r\n  <string>gi</string>\r\n  <string>give" +
            "</string>\r\n  <string>given</string>\r\n  <string>gives</string>\r\n  <string>giving<" +
            "/string>\r\n  <string>gl</string>\r\n  <string>gm</string>\r\n  <string>gmt</string>\r\n" +
            "  <string>gn</string>\r\n  <string>go</string>\r\n  <string>goes</string>\r\n  <string" +
            ">going</string>\r\n  <string>gone</string>\r\n  <string>good</string>\r\n  <string>goo" +
            "ds</string>\r\n  <string>got</string>\r\n  <string>gotten</string>\r\n  <string>gov</s" +
            "tring>\r\n  <string>gp</string>\r\n  <string>gq</string>\r\n  <string>gr</string>\r\n  <" +
            "string>great</string>\r\n  <string>greater</string>\r\n  <string>greatest</string>\r\n" +
            "  <string>greetings</string>\r\n  <string>group</string>\r\n  <string>grouped</strin" +
            "g>\r\n  <string>grouping</string>\r\n  <string>groups</string>\r\n  <string>gs</string" +
            ">\r\n  <string>gt</string>\r\n  <string>gu</string>\r\n  <string>gw</string>\r\n  <strin" +
            "g>gy</string>\r\n  <string>h</string>\r\n  <string>had</string>\r\n  <string>hadn\'t</s" +
            "tring>\r\n  <string>hadnt</string>\r\n  <string>half</string>\r\n  <string>happens</st" +
            "ring>\r\n  <string>hardly</string>\r\n  <string>has</string>\r\n  <string>hasn</string" +
            ">\r\n  <string>hasn\'t</string>\r\n  <string>hasnt</string>\r\n  <string>have</string>\r" +
            "\n  <string>haven</string>\r\n  <string>haven\'t</string>\r\n  <string>havent</string>" +
            "\r\n  <string>having</string>\r\n  <string>he</string>\r\n  <string>he\'d</string>\r\n  <" +
            "string>he\'ll</string>\r\n  <string>he\'s</string>\r\n  <string>hed</string>\r\n  <strin" +
            "g>hell</string>\r\n  <string>hello</string>\r\n  <string>help</string>\r\n  <string>he" +
            "nce</string>\r\n  <string>her</string>\r\n  <string>here</string>\r\n  <string>here\'s<" +
            "/string>\r\n  <string>hereafter</string>\r\n  <string>hereby</string>\r\n  <string>her" +
            "ein</string>\r\n  <string>heres</string>\r\n  <string>hereupon</string>\r\n  <string>h" +
            "ers</string>\r\n  <string>herself</string>\r\n  <string>herse”</string>\r\n  <string>h" +
            "es</string>\r\n  <string>hi</string>\r\n  <string>hid</string>\r\n  <string>high</stri" +
            "ng>\r\n  <string>higher</string>\r\n  <string>highest</string>\r\n  <string>him</strin" +
            "g>\r\n  <string>himself</string>\r\n  <string>himse”</string>\r\n  <string>his</string" +
            ">\r\n  <string>hither</string>\r\n  <string>hk</string>\r\n  <string>hm</string>\r\n  <s" +
            "tring>hn</string>\r\n  <string>home</string>\r\n  <string>homepage</string>\r\n  <stri" +
            "ng>hopefully</string>\r\n  <string>how</string>\r\n  <string>how\'d</string>\r\n  <stri" +
            "ng>how\'ll</string>\r\n  <string>how\'s</string>\r\n  <string>howbeit</string>\r\n  <str" +
            "ing>however</string>\r\n  <string>hr</string>\r\n  <string>ht</string>\r\n  <string>ht" +
            "m</string>\r\n  <string>html</string>\r\n  <string>http</string>\r\n  <string>hu</stri" +
            "ng>\r\n  <string>hundred</string>\r\n  <string>i</string>\r\n  <string>i\'d</string>\r\n " +
            " <string>i\'ll</string>\r\n  <string>i\'m</string>\r\n  <string>i\'ve</string>\r\n  <stri" +
            "ng>i.e.</string>\r\n  <string>id</string>\r\n  <string>ie</string>\r\n  <string>if</st" +
            "ring>\r\n  <string>ignored</string>\r\n  <string>ii</string>\r\n  <string>il</string>\r" +
            "\n  <string>ill</string>\r\n  <string>im</string>\r\n  <string>immediate</string>\r\n  " +
            "<string>immediately</string>\r\n  <string>importance</string>\r\n  <string>important" +
            "</string>\r\n  <string>in</string>\r\n  <string>inasmuch</string>\r\n  <string>inc</st" +
            "ring>\r\n  <string>inc.</string>\r\n  <string>indeed</string>\r\n  <string>index</stri" +
            "ng>\r\n  <string>indicate</string>\r\n  <string>indicated</string>\r\n  <string>indica" +
            "tes</string>\r\n  <string>information</string>\r\n  <string>inner</string>\r\n  <strin" +
            "g>inside</string>\r\n  <string>insofar</string>\r\n  <string>instead</string>\r\n  <st" +
            "ring>int</string>\r\n  <string>interest</string>\r\n  <string>interested</string>\r\n " +
            " <string>interesting</string>\r\n  <string>interests</string>\r\n  <string>into</str" +
            "ing>\r\n  <string>invention</string>\r\n  <string>inward</string>\r\n  <string>io</str" +
            "ing>\r\n  <string>iq</string>\r\n  <string>ir</string>\r\n  <string>is</string>\r\n  <st" +
            "ring>isn</string>\r\n  <string>isn\'t</string>\r\n  <string>isnt</string>\r\n  <string>" +
            "it</string>\r\n  <string>it\'d</string>\r\n  <string>it\'ll</string>\r\n  <string>it\'s</" +
            "string>\r\n  <string>itd</string>\r\n  <string>itll</string>\r\n  <string>its</string>" +
            "\r\n  <string>itself</string>\r\n  <string>itse”</string>\r\n  <string>ive</string>\r\n " +
            " <string>j</string>\r\n  <string>je</string>\r\n  <string>jm</string>\r\n  <string>jo<" +
            "/string>\r\n  <string>join</string>\r\n  <string>jp</string>\r\n  <string>just</string" +
            ">\r\n  <string>k</string>\r\n  <string>ke</string>\r\n  <string>keep</string>\r\n  <stri" +
            "ng>keeps</string>\r\n  <string>kept</string>\r\n  <string>keys</string>\r\n  <string>k" +
            "g</string>\r\n  <string>kh</string>\r\n  <string>ki</string>\r\n  <string>kind</string" +
            ">\r\n  <string>km</string>\r\n  <string>kn</string>\r\n  <string>knew</string>\r\n  <str" +
            "ing>know</string>\r\n  <string>known</string>\r\n  <string>knows</string>\r\n  <string" +
            ">kp</string>\r\n  <string>kr</string>\r\n  <string>kw</string>\r\n  <string>ky</string" +
            ">\r\n  <string>kz</string>\r\n  <string>l</string>\r\n  <string>la</string>\r\n  <string" +
            ">large</string>\r\n  <string>largely</string>\r\n  <string>last</string>\r\n  <string>" +
            "lately</string>\r\n  <string>later</string>\r\n  <string>latest</string>\r\n  <string>" +
            "latter</string>\r\n  <string>latterly</string>\r\n  <string>lb</string>\r\n  <string>l" +
            "c</string>\r\n  <string>least</string>\r\n  <string>length</string>\r\n  <string>less<" +
            "/string>\r\n  <string>lest</string>\r\n  <string>let</string>\r\n  <string>let\'s</stri" +
            "ng>\r\n  <string>lets</string>\r\n  <string>li</string>\r\n  <string>like</string>\r\n  " +
            "<string>liked</string>\r\n  <string>likely</string>\r\n  <string>likewise</string>\r\n" +
            "  <string>line</string>\r\n  <string>little</string>\r\n  <string>lk</string>\r\n  <st" +
            "ring>ll</string>\r\n  <string>long</string>\r\n  <string>longer</string>\r\n  <string>" +
            "longest</string>\r\n  <string>look</string>\r\n  <string>looking</string>\r\n  <string" +
            ">looks</string>\r\n  <string>low</string>\r\n  <string>lower</string>\r\n  <string>lr<" +
            "/string>\r\n  <string>ls</string>\r\n  <string>lt</string>\r\n  <string>ltd</string>\r\n" +
            "  <string>lu</string>\r\n  <string>lv</string>\r\n  <string>ly</string>\r\n  <string>m" +
            "</string>\r\n  <string>ma</string>\r\n  <string>made</string>\r\n  <string>mainly</str" +
            "ing>\r\n  <string>make</string>\r\n  <string>makes</string>\r\n  <string>making</strin" +
            "g>\r\n  <string>man</string>\r\n  <string>many</string>\r\n  <string>may</string>\r\n  <" +
            "string>maybe</string>\r\n  <string>mayn\'t</string>\r\n  <string>maynt</string>\r\n  <s" +
            "tring>mc</string>\r\n  <string>md</string>\r\n  <string>me</string>\r\n  <string>mean<" +
            "/string>\r\n  <string>means</string>\r\n  <string>meantime</string>\r\n  <string>meanw" +
            "hile</string>\r\n  <string>member</string>\r\n  <string>members</string>\r\n  <string>" +
            "men</string>\r\n  <string>merely</string>\r\n  <string>mg</string>\r\n  <string>mh</st" +
            "ring>\r\n  <string>microsoft</string>\r\n  <string>might</string>\r\n  <string>might\'v" +
            "e</string>\r\n  <string>mightn\'t</string>\r\n  <string>mightnt</string>\r\n  <string>m" +
            "il</string>\r\n  <string>mill</string>\r\n  <string>million</string>\r\n  <string>mine" +
            "</string>\r\n  <string>minus</string>\r\n  <string>miss</string>\r\n  <string>mk</stri" +
            "ng>\r\n  <string>ml</string>\r\n  <string>mm</string>\r\n  <string>mn</string>\r\n  <str" +
            "ing>mo</string>\r\n  <string>more</string>\r\n  <string>moreover</string>\r\n  <string" +
            ">most</string>\r\n  <string>mostly</string>\r\n  <string>move</string>\r\n  <string>mp" +
            "</string>\r\n  <string>mq</string>\r\n  <string>mr</string>\r\n  <string>mrs</string>\r" +
            "\n  <string>ms</string>\r\n  <string>msie</string>\r\n  <string>mt</string>\r\n  <strin" +
            "g>mu</string>\r\n  <string>much</string>\r\n  <string>mug</string>\r\n  <string>must</" +
            "string>\r\n  <string>must\'ve</string>\r\n  <string>mustn\'t</string>\r\n  <string>mustn" +
            "t</string>\r\n  <string>mv</string>\r\n  <string>mw</string>\r\n  <string>mx</string>\r" +
            "\n  <string>my</string>\r\n  <string>myself</string>\r\n  <string>myse”</string>\r\n  <" +
            "string>mz</string>\r\n  <string>n</string>\r\n  <string>na</string>\r\n  <string>name<" +
            "/string>\r\n  <string>namely</string>\r\n  <string>nay</string>\r\n  <string>nc</strin" +
            "g>\r\n  <string>nd</string>\r\n  <string>ne</string>\r\n  <string>near</string>\r\n  <st" +
            "ring>nearly</string>\r\n  <string>necessarily</string>\r\n  <string>necessary</strin" +
            "g>\r\n  <string>need</string>\r\n  <string>needed</string>\r\n  <string>needing</strin" +
            "g>\r\n  <string>needn\'t</string>\r\n  <string>neednt</string>\r\n  <string>needs</stri" +
            "ng>\r\n  <string>neither</string>\r\n  <string>net</string>\r\n  <string>netscape</str" +
            "ing>\r\n  <string>never</string>\r\n  <string>neverf</string>\r\n  <string>neverless</" +
            "string>\r\n  <string>nevertheless</string>\r\n  <string>new</string>\r\n  <string>newe" +
            "r</string>\r\n  <string>newest</string>\r\n  <string>next</string>\r\n  <string>nf</st" +
            "ring>\r\n  <string>ng</string>\r\n  <string>ni</string>\r\n  <string>nine</string>\r\n  " +
            "<string>ninety</string>\r\n  <string>nl</string>\r\n  <string>no</string>\r\n  <string" +
            ">no-one</string>\r\n  <string>nobody</string>\r\n  <string>non</string>\r\n  <string>n" +
            "one</string>\r\n  <string>nonetheless</string>\r\n  <string>noone</string>\r\n  <strin" +
            "g>nor</string>\r\n  <string>normally</string>\r\n  <string>nos</string>\r\n  <string>n" +
            "ot</string>\r\n  <string>noted</string>\r\n  <string>nothing</string>\r\n  <string>not" +
            "withstanding</string>\r\n  <string>novel</string>\r\n  <string>now</string>\r\n  <stri" +
            "ng>nowhere</string>\r\n  <string>np</string>\r\n  <string>nr</string>\r\n  <string>nu<" +
            "/string>\r\n  <string>null</string>\r\n  <string>number</string>\r\n  <string>numbers<" +
            "/string>\r\n  <string>nz</string>\r\n  <string>o</string>\r\n  <string>obtain</string>" +
            "\r\n  <string>obtained</string>\r\n  <string>obviously</string>\r\n  <string>of</strin" +
            "g>\r\n  <string>off</string>\r\n  <string>often</string>\r\n  <string>oh</string>\r\n  <" +
            "string>ok</string>\r\n  <string>okay</string>\r\n  <string>old</string>\r\n  <string>o" +
            "lder</string>\r\n  <string>oldest</string>\r\n  <string>om</string>\r\n  <string>omitt" +
            "ed</string>\r\n  <string>on</string>\r\n  <string>once</string>\r\n  <string>one</stri" +
            "ng>\r\n  <string>one\'s</string>\r\n  <string>ones</string>\r\n  <string>only</string>\r" +
            "\n  <string>onto</string>\r\n  <string>open</string>\r\n  <string>opened</string>\r\n  " +
            "<string>opening</string>\r\n  <string>opens</string>\r\n  <string>opposite</string>\r" +
            "\n  <string>or</string>\r\n  <string>ord</string>\r\n  <string>order</string>\r\n  <str" +
            "ing>ordered</string>\r\n  <string>ordering</string>\r\n  <string>orders</string>\r\n  " +
            "<string>org</string>\r\n  <string>other</string>\r\n  <string>others</string>\r\n  <st" +
            "ring>otherwise</string>\r\n  <string>ought</string>\r\n  <string>oughtn\'t</string>\r\n" +
            "  <string>oughtnt</string>\r\n  <string>our</string>\r\n  <string>ours</string>\r\n  <" +
            "string>ourselves</string>\r\n  <string>out</string>\r\n  <string>outside</string>\r\n " +
            " <string>over</string>\r\n  <string>overall</string>\r\n  <string>owing</string>\r\n  " +
            "<string>own</string>\r\n  <string>p</string>\r\n  <string>pa</string>\r\n  <string>pag" +
            "e</string>\r\n  <string>pages</string>\r\n  <string>part</string>\r\n  <string>parted<" +
            "/string>\r\n  <string>particular</string>\r\n  <string>particularly</string>\r\n  <str" +
            "ing>parting</string>\r\n  <string>parts</string>\r\n  <string>past</string>\r\n  <stri" +
            "ng>pe</string>\r\n  <string>per</string>\r\n  <string>perhaps</string>\r\n  <string>pf" +
            "</string>\r\n  <string>pg</string>\r\n  <string>ph</string>\r\n  <string>pk</string>\r\n" +
            "  <string>pl</string>\r\n  <string>place</string>\r\n  <string>placed</string>\r\n  <s" +
            "tring>places</string>\r\n  <string>please</string>\r\n  <string>plus</string>\r\n  <st" +
            "ring>pm</string>\r\n  <string>pmid</string>\r\n  <string>pn</string>\r\n  <string>poin" +
            "t</string>\r\n  <string>pointed</string>\r\n  <string>pointing</string>\r\n  <string>p" +
            "oints</string>\r\n  <string>poorly</string>\r\n  <string>possible</string>\r\n  <strin" +
            "g>possibly</string>\r\n  <string>potentially</string>\r\n  <string>pp</string>\r\n  <s" +
            "tring>pr</string>\r\n  <string>predominantly</string>\r\n  <string>present</string>\r" +
            "\n  <string>presented</string>\r\n  <string>presenting</string>\r\n  <string>presents" +
            "</string>\r\n  <string>presumably</string>\r\n  <string>previously</string>\r\n  <stri" +
            "ng>primarily</string>\r\n  <string>probably</string>\r\n  <string>problem</string>\r\n" +
            "  <string>problems</string>\r\n  <string>promptly</string>\r\n  <string>proud</strin" +
            "g>\r\n  <string>provided</string>\r\n  <string>provides</string>\r\n  <string>pt</stri" +
            "ng>\r\n  <string>put</string>\r\n  <string>puts</string>\r\n  <string>pw</string>\r\n  <" +
            "string>py</string>\r\n  <string>q</string>\r\n  <string>qa</string>\r\n  <string>que</" +
            "string>\r\n  <string>quickly</string>\r\n  <string>quite</string>\r\n  <string>qv</str" +
            "ing>\r\n  <string>r</string>\r\n  <string>ran</string>\r\n  <string>rather</string>\r\n " +
            " <string>rd</string>\r\n  <string>re</string>\r\n  <string>readily</string>\r\n  <stri" +
            "ng>really</string>\r\n  <string>reasonably</string>\r\n  <string>recent</string>\r\n  " +
            "<string>recently</string>\r\n  <string>ref</string>\r\n  <string>refs</string>\r\n  <s" +
            "tring>regarding</string>\r\n  <string>regardless</string>\r\n  <string>regards</stri" +
            "ng>\r\n  <string>related</string>\r\n  <string>relatively</string>\r\n  <string>resear" +
            "ch</string>\r\n  <string>reserved</string>\r\n  <string>respectively</string>\r\n  <st" +
            "ring>resulted</string>\r\n  <string>resulting</string>\r\n  <string>results</string>" +
            "\r\n  <string>right</string>\r\n  <string>ring</string>\r\n  <string>ro</string>\r\n  <s" +
            "tring>room</string>\r\n  <string>rooms</string>\r\n  <string>round</string>\r\n  <stri" +
            "ng>ru</string>\r\n  <string>run</string>\r\n  <string>rw</string>\r\n  <string>s</stri" +
            "ng>\r\n  <string>sa</string>\r\n  <string>said</string>\r\n  <string>same</string>\r\n  " +
            "<string>saw</string>\r\n  <string>say</string>\r\n  <string>saying</string>\r\n  <stri" +
            "ng>says</string>\r\n  <string>sb</string>\r\n  <string>sc</string>\r\n  <string>sd</st" +
            "ring>\r\n  <string>se</string>\r\n  <string>sec</string>\r\n  <string>second</string>\r" +
            "\n  <string>secondly</string>\r\n  <string>seconds</string>\r\n  <string>section</str" +
            "ing>\r\n  <string>see</string>\r\n  <string>seeing</string>\r\n  <string>seem</string>" +
            "\r\n  <string>seemed</string>\r\n  <string>seeming</string>\r\n  <string>seems</string" +
            ">\r\n  <string>seen</string>\r\n  <string>sees</string>\r\n  <string>self</string>\r\n  " +
            "<string>selves</string>\r\n  <string>sensible</string>\r\n  <string>sent</string>\r\n " +
            " <string>serious</string>\r\n  <string>seriously</string>\r\n  <string>seven</string" +
            ">\r\n  <string>seventy</string>\r\n  <string>several</string>\r\n  <string>sg</string>" +
            "\r\n  <string>sh</string>\r\n  <string>shall</string>\r\n  <string>shan\'t</string>\r\n  " +
            "<string>shant</string>\r\n  <string>she</string>\r\n  <string>she\'d</string>\r\n  <str" +
            "ing>she\'ll</string>\r\n  <string>she\'s</string>\r\n  <string>shed</string>\r\n  <strin" +
            "g>shell</string>\r\n  <string>shes</string>\r\n  <string>should</string>\r\n  <string>" +
            "should\'ve</string>\r\n  <string>shouldn</string>\r\n  <string>shouldn\'t</string>\r\n  " +
            "<string>shouldnt</string>\r\n  <string>show</string>\r\n  <string>showed</string>\r\n " +
            " <string>showing</string>\r\n  <string>shown</string>\r\n  <string>showns</string>\r\n" +
            "  <string>shows</string>\r\n  <string>si</string>\r\n  <string>side</string>\r\n  <str" +
            "ing>sides</string>\r\n  <string>significant</string>\r\n  <string>significantly</str" +
            "ing>\r\n  <string>similar</string>\r\n  <string>similarly</string>\r\n  <string>since<" +
            "/string>\r\n  <string>sincere</string>\r\n  <string>site</string>\r\n  <string>six</st" +
            "ring>\r\n  <string>sixty</string>\r\n  <string>sj</string>\r\n  <string>sk</string>\r\n " +
            " <string>sl</string>\r\n  <string>slightly</string>\r\n  <string>sm</string>\r\n  <str" +
            "ing>small</string>\r\n  <string>smaller</string>\r\n  <string>smallest</string>\r\n  <" +
            "string>sn</string>\r\n  <string>so</string>\r\n  <string>some</string>\r\n  <string>so" +
            "mebody</string>\r\n  <string>someday</string>\r\n  <string>somehow</string>\r\n  <stri" +
            "ng>someone</string>\r\n  <string>somethan</string>\r\n  <string>something</string>\r\n" +
            "  <string>sometime</string>\r\n  <string>sometimes</string>\r\n  <string>somewhat</s" +
            "tring>\r\n  <string>somewhere</string>\r\n  <string>soon</string>\r\n  <string>sorry</" +
            "string>\r\n  <string>specifically</string>\r\n  <string>specified</string>\r\n  <strin" +
            "g>specify</string>\r\n  <string>specifying</string>\r\n  <string>sr</string>\r\n  <str" +
            "ing>st</string>\r\n  <string>state</string>\r\n  <string>states</string>\r\n  <string>" +
            "still</string>\r\n  <string>stop</string>\r\n  <string>strongly</string>\r\n  <string>" +
            "su</string>\r\n  <string>sub</string>\r\n  <string>substantially</string>\r\n  <string" +
            ">successfully</string>\r\n  <string>such</string>\r\n  <string>sufficiently</string>" +
            "\r\n  <string>suggest</string>\r\n  <string>sup</string>\r\n  <string>sure</string>\r\n " +
            " <string>sv</string>\r\n  <string>sy</string>\r\n  <string>system</string>\r\n  <strin" +
            "g>sz</string>\r\n  <string>t</string>\r\n  <string>t\'s</string>\r\n  <string>take</str" +
            "ing>\r\n  <string>taken</string>\r\n  <string>taking</string>\r\n  <string>tc</string>" +
            "\r\n  <string>td</string>\r\n  <string>tell</string>\r\n  <string>ten</string>\r\n  <str" +
            "ing>tends</string>\r\n  <string>test</string>\r\n  <string>text</string>\r\n  <string>" +
            "tf</string>\r\n  <string>tg</string>\r\n  <string>th</string>\r\n  <string>than</strin" +
            "g>\r\n  <string>thank</string>\r\n  <string>thanks</string>\r\n  <string>thanx</string" +
            ">\r\n  <string>that</string>\r\n  <string>that\'ll</string>\r\n  <string>that\'s</string" +
            ">\r\n  <string>that\'ve</string>\r\n  <string>thatll</string>\r\n  <string>thats</strin" +
            "g>\r\n  <string>thatve</string>\r\n  <string>the</string>\r\n  <string>their</string>\r" +
            "\n  <string>theirs</string>\r\n  <string>them</string>\r\n  <string>themselves</strin" +
            "g>\r\n  <string>then</string>\r\n  <string>thence</string>\r\n  <string>there</string>" +
            "\r\n  <string>there\'d</string>\r\n  <string>there\'ll</string>\r\n  <string>there\'re</s" +
            "tring>\r\n  <string>there\'s</string>\r\n  <string>there\'ve</string>\r\n  <string>there" +
            "after</string>\r\n  <string>thereby</string>\r\n  <string>thered</string>\r\n  <string" +
            ">therefore</string>\r\n  <string>therein</string>\r\n  <string>therell</string>\r\n  <" +
            "string>thereof</string>\r\n  <string>therere</string>\r\n  <string>theres</string>\r\n" +
            "  <string>thereto</string>\r\n  <string>thereupon</string>\r\n  <string>thereve</str" +
            "ing>\r\n  <string>these</string>\r\n  <string>they</string>\r\n  <string>they\'d</strin" +
            "g>\r\n  <string>they\'ll</string>\r\n  <string>they\'re</string>\r\n  <string>they\'ve</s" +
            "tring>\r\n  <string>theyd</string>\r\n  <string>theyll</string>\r\n  <string>theyre</s" +
            "tring>\r\n  <string>theyve</string>\r\n  <string>thick</string>\r\n  <string>thin</str" +
            "ing>\r\n  <string>thing</string>\r\n  <string>things</string>\r\n  <string>think</stri" +
            "ng>\r\n  <string>thinks</string>\r\n  <string>third</string>\r\n  <string>thirty</stri" +
            "ng>\r\n  <string>this</string>\r\n  <string>thorough</string>\r\n  <string>thoroughly<" +
            "/string>\r\n  <string>those</string>\r\n  <string>thou</string>\r\n  <string>though</s" +
            "tring>\r\n  <string>thoughh</string>\r\n  <string>thought</string>\r\n  <string>though" +
            "ts</string>\r\n  <string>thousand</string>\r\n  <string>three</string>\r\n  <string>th" +
            "roug</string>\r\n  <string>through</string>\r\n  <string>throughout</string>\r\n  <str" +
            "ing>thru</string>\r\n  <string>thus</string>\r\n  <string>til</string>\r\n  <string>ti" +
            "ll</string>\r\n  <string>tip</string>\r\n  <string>tis</string>\r\n  <string>tj</strin" +
            "g>\r\n  <string>tk</string>\r\n  <string>tm</string>\r\n  <string>tn</string>\r\n  <stri" +
            "ng>to</string>\r\n  <string>today</string>\r\n  <string>together</string>\r\n  <string" +
            ">too</string>\r\n  <string>took</string>\r\n  <string>top</string>\r\n  <string>toward" +
            "</string>\r\n  <string>towards</string>\r\n  <string>tp</string>\r\n  <string>tr</stri" +
            "ng>\r\n  <string>tried</string>\r\n  <string>tries</string>\r\n  <string>trillion</str" +
            "ing>\r\n  <string>truly</string>\r\n  <string>try</string>\r\n  <string>trying</string" +
            ">\r\n  <string>ts</string>\r\n  <string>tt</string>\r\n  <string>turn</string>\r\n  <str" +
            "ing>turned</string>\r\n  <string>turning</string>\r\n  <string>turns</string>\r\n  <st" +
            "ring>tv</string>\r\n  <string>tw</string>\r\n  <string>twas</string>\r\n  <string>twel" +
            "ve</string>\r\n  <string>twenty</string>\r\n  <string>twice</string>\r\n  <string>two<" +
            "/string>\r\n  <string>tz</string>\r\n  <string>u</string>\r\n  <string>ua</string>\r\n  " +
            "<string>ug</string>\r\n  <string>uk</string>\r\n  <string>um</string>\r\n  <string>un<" +
            "/string>\r\n  <string>under</string>\r\n  <string>underneath</string>\r\n  <string>und" +
            "oing</string>\r\n  <string>unfortunately</string>\r\n  <string>unless</string>\r\n  <s" +
            "tring>unlike</string>\r\n  <string>unlikely</string>\r\n  <string>until</string>\r\n  " +
            "<string>unto</string>\r\n  <string>up</string>\r\n  <string>upon</string>\r\n  <string" +
            ">ups</string>\r\n  <string>upwards</string>\r\n  <string>us</string>\r\n  <string>use<" +
            "/string>\r\n  <string>used</string>\r\n  <string>useful</string>\r\n  <string>usefully" +
            "</string>\r\n  <string>usefulness</string>\r\n  <string>uses</string>\r\n  <string>usi" +
            "ng</string>\r\n  <string>usually</string>\r\n  <string>uucp</string>\r\n  <string>uy</" +
            "string>\r\n  <string>uz</string>\r\n  <string>v</string>\r\n  <string>va</string>\r\n  <" +
            "string>value</string>\r\n  <string>various</string>\r\n  <string>vc</string>\r\n  <str" +
            "ing>ve</string>\r\n  <string>versus</string>\r\n  <string>very</string>\r\n  <string>v" +
            "g</string>\r\n  <string>vi</string>\r\n  <string>via</string>\r\n  <string>viz</string" +
            ">\r\n  <string>vn</string>\r\n  <string>vol</string>\r\n  <string>vols</string>\r\n  <st" +
            "ring>vs</string>\r\n  <string>vu</string>\r\n  <string>w</string>\r\n  <string>want</s" +
            "tring>\r\n  <string>wanted</string>\r\n  <string>wanting</string>\r\n  <string>wants</" +
            "string>\r\n  <string>was</string>\r\n  <string>wasn</string>\r\n  <string>wasn\'t</stri" +
            "ng>\r\n  <string>wasnt</string>\r\n  <string>way</string>\r\n  <string>ways</string>\r\n" +
            "  <string>we</string>\r\n  <string>we\'d</string>\r\n  <string>we\'ll</string>\r\n  <str" +
            "ing>we\'re</string>\r\n  <string>we\'ve</string>\r\n  <string>web</string>\r\n  <string>" +
            "webpage</string>\r\n  <string>website</string>\r\n  <string>wed</string>\r\n  <string>" +
            "welcome</string>\r\n  <string>well</string>\r\n  <string>wells</string>\r\n  <string>w" +
            "ent</string>\r\n  <string>were</string>\r\n  <string>weren</string>\r\n  <string>weren" +
            "\'t</string>\r\n  <string>werent</string>\r\n  <string>weve</string>\r\n  <string>wf</s" +
            "tring>\r\n  <string>what</string>\r\n  <string>what\'d</string>\r\n  <string>what\'ll</s" +
            "tring>\r\n  <string>what\'s</string>\r\n  <string>what\'ve</string>\r\n  <string>whateve" +
            "r</string>\r\n  <string>whatll</string>\r\n  <string>whats</string>\r\n  <string>whatv" +
            "e</string>\r\n  <string>when</string>\r\n  <string>when\'d</string>\r\n  <string>when\'l" +
            "l</string>\r\n  <string>when\'s</string>\r\n  <string>whence</string>\r\n  <string>when" +
            "ever</string>\r\n  <string>where</string>\r\n  <string>where\'d</string>\r\n  <string>w" +
            "here\'ll</string>\r\n  <string>where\'s</string>\r\n  <string>whereafter</string>\r\n  <" +
            "string>whereas</string>\r\n  <string>whereby</string>\r\n  <string>wherein</string>\r" +
            "\n  <string>wheres</string>\r\n  <string>whereupon</string>\r\n  <string>wherever</st" +
            "ring>\r\n  <string>whether</string>\r\n  <string>which</string>\r\n  <string>whichever" +
            "</string>\r\n  <string>while</string>\r\n  <string>whilst</string>\r\n  <string>whim</" +
            "string>\r\n  <string>whither</string>\r\n  <string>who</string>\r\n  <string>who\'d</st" +
            "ring>\r\n  <string>who\'ll</string>\r\n  <string>who\'s</string>\r\n  <string>whod</stri" +
            "ng>\r\n  <string>whoever</string>\r\n  <string>whole</string>\r\n  <string>wholl</stri" +
            "ng>\r\n  <string>whom</string>\r\n  <string>whomever</string>\r\n  <string>whos</strin" +
            "g>\r\n  <string>whose</string>\r\n  <string>why</string>\r\n  <string>why\'d</string>\r\n" +
            "  <string>why\'ll</string>\r\n  <string>why\'s</string>\r\n  <string>widely</string>\r\n" +
            "  <string>width</string>\r\n  <string>will</string>\r\n  <string>willing</string>\r\n " +
            " <string>wish</string>\r\n  <string>with</string>\r\n  <string>within</string>\r\n  <s" +
            "tring>without</string>\r\n  <string>won</string>\r\n  <string>won\'t</string>\r\n  <str" +
            "ing>wonder</string>\r\n  <string>wont</string>\r\n  <string>words</string>\r\n  <strin" +
            "g>work</string>\r\n  <string>worked</string>\r\n  <string>working</string>\r\n  <strin" +
            "g>works</string>\r\n  <string>world</string>\r\n  <string>would</string>\r\n  <string>" +
            "would\'ve</string>\r\n  <string>wouldn</string>\r\n  <string>wouldn\'t</string>\r\n  <st" +
            "ring>wouldnt</string>\r\n  <string>ws</string>\r\n  <string>www</string>\r\n  <string>" +
            "x</string>\r\n  <string>y</string>\r\n  <string>ye</string>\r\n  <string>year</string>" +
            "\r\n  <string>years</string>\r\n  <string>yes</string>\r\n  <string>yet</string>\r\n  <s" +
            "tring>you</string>\r\n  <string>you\'d</string>\r\n  <string>you\'ll</string>\r\n  <stri" +
            "ng>you\'re</string>\r\n  <string>you\'ve</string>\r\n  <string>youd</string>\r\n  <strin" +
            "g>youll</string>\r\n  <string>young</string>\r\n  <string>younger</string>\r\n  <strin" +
            "g>youngest</string>\r\n  <string>your</string>\r\n  <string>youre</string>\r\n  <strin" +
            "g>yours</string>\r\n  <string>yourself</string>\r\n  <string>yourselves</string>\r\n  " +
            "<string>youve</string>\r\n  <string>yt</string>\r\n  <string>yu</string>\r\n  <string>" +
            "z</string>\r\n  <string>za</string>\r\n  <string>zero</string>\r\n  <string>zm</string" +
            ">\r\n  <string>zr</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StopWords {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StopWords"]));
            }
        }
    }
}
